apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spinnvill
  namespace: tbd
  labels:
    team: tbd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spinnvill
  minReplicas: {{ minReplicas }}
  maxReplicas: {{ maxReplicas }}
  metrics:
    - type: External
      external:
        metric:
          name: kafka_consumergroup_group_lag
          selector:
            matchLabels:
              topic: tbd.rapid.v1
              group: tbd-spinnvill-v1
        target:
          type: AverageValue
          averageValue: 1000
  behavior:
    scaleUp:
      policies:
        - type: Pods
          periodSeconds: 15
          value: 2
      stabilizationWindowSeconds: 10
    scaleDown:
      policies:
        - type: Pods
          value: 3
          periodSeconds: 30
      stabilizationWindowSeconds: 30
