apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: spinnvill-db-policy-dev
  namespace: tbd
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 35.228.132.39/32
  podSelector:
    matchLabels:
      db_policy_user: spinnvillbruker
  policyTypes:
    - Egress