apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    team: tbd
  name: spinnvill
  namespace: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        diskAutoresize: true
        databases:
          - name: spinnvill
            envVarPrefix: DATABASE
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spinnvill-v1
