name: Bygg og deploy Spinnvill-opprydding-dev

on:
  push:
    paths:
      - 'Dockerfile-opprydding-dev'
      - 'spinnvill-opprydding-dev/**'
      - 'spinnvill-felles/**'
      - 'build.gradle.kts'
      - '.github/workflows/opprydding-dev.yml'
      - 'deploy/dev-opprydding.yml'
      - 'deploy/dev-db-policy.yml'
      - '.dockerignore'
    branches:
      - main
jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    name: Bygg, test og lag docker image
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4
      - name: Sett opp Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21.x"
      - name: Bygg med Gradle
        uses: gradle/gradle-build-action@v2.10.0
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew :spinnvill-opprydding-dev:test :spinnvill-opprydding-dev:build
      - name: Bygg docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tbd
          cache_from: type=gha
          cache_to: type=gha,mode=min
          dockerfile: Dockerfile-opprydding-dev
          image_suffix: opprydding-dev
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-dev:
    name: Deploy til dev
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4
      - name: Deploy til NAIS
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/dev-opprydding.yml
          IMAGE: ${{ needs.build.outputs.image }}
